### ISSUE TITLE
SCSS add ability to use keyframe animations

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#109]
**What can't you do?**
Keyframe animations

**How would you like it to work?**
```scss
@keyframes scroll {
    0% {
        background-position: right 0px bottom 0px;
    }

    100% {
        background-position: right 1000px bottom 1000px;
    }
}
```

**What have you tried?**
N/A

**Additional context**
