### ISSUE TITLE
SCSS `box-shadow` sometimes ignores individually-set corner radiuses

### ISSUE THREAD

**Issue by TheBerkin** [Facepunch/sbox-issues#110]
**Describe the bug**
When using `box-shadow` on an element, the shadow sometimes renders incorrectly if the element has a `border-radius` with individually-set corner values (e.g. `border-radius: 0 100% 100% 0`).

The bug does not occur when passing a single value to `border-radius` (e.g. `border-radius: 12px`).

**To Reproduce**

1. Make a panel
2. Add this style to it:
```scss
.broken {
    width: 480px;
    height: 100px;
    background-color: #36e;
    border-radius: 0 100% 100% 0;
    box-shadow: 0 0 24px 4px black;
}
```

**Expected behavior**
The shadow should always render with correct corner radiuses.

**Screenshots**

![image](https://user-images.githubusercontent.com/1622492/117472470-89295880-af1e-11eb-8907-bc5671d03fc2.png)
