### ISSUE TITLE
SCSS Ampersand behavior isn't correct

### ISSUE THREAD

**Issue by ShoarW** [Facepunch/sbox-issues#14]
I'm not sure how deep you guys are trying to replicate SCSS & HTML but there's behavior that I can see is incorrect/doesn't work

`
.main {
  &:disabled {
    background-color: red;
  }
}
`

`
<div class="main">
</div>
`
Expected: Element is not red (i.e The element goes red when the disabled attribute is added to the element)
Actual: The element is red

`.main {
  display: flex;
  align-items: center;

  &__logo {
    background: url(/ui/settlers-logo.png);
    background-size: contain;
    background-repeat: no-repeat;
    width: 305px;
    height: 184px;
  }
  `

`
<div class="main">
  <div class="main__logo"></div>
</div>
`
Expected: .main__logo to be generated
Actual: Does not appear to be created, if I create the class manually (i.e. .main__logo) it'll show up.

**Comment by garrynewman** [comment]
It's not really our wish to be 100% compatible, but these selectors seem common enough that we should try to support them.

**Comment by ShoarW** [comment]
Sure - I can agree with supporting at least the common operators but it may cause confusion to those who use SCSS more regularly, especially when you get into the real benefits of SCSS with mixins, maps etc. I do like s&box's version of it more than just regular CSS though since we're not building websites and everything is still technically possible.

**Comment by SebbeJohansson** [comment]
I encountered this now in 2024. I tried to do:
```scss
.fill {
	height: 100%;
	width: 100%;
	position: absolute;
	top: 0;
	left: 0;
	&--health {
		background-color: rgb(180, 71, 71);
	}
	&--food {
		background-color: rgb(219, 157, 42);
	}
}
```
And it isn't generating the right classes.

@garrynewman is there a plan to eventually fix this?
