### ISSUE TITLE
SCSS Variables not supported

### ISSUE THREAD

**Issue by ShoarW** [Facepunch/sbox-issues#15]
```scss
$theme-color: red;

.button {
    background-color: rgba($theme-color, .2);
}

.link {
    background-color: rgba($theme-color, .8);
}
```

Fails with: `Error parsing stylesheet: Parse Error, unexpected character ; [/hud.scss:0]
