### ISSUE TITLE
Text artifacting

### ISSUE THREAD

**Issue by TomDotBat** [Facepunch/sbox-issues#157]
**Describe the bug**
Text rendering has visible artificating in many places of the UI.

**To Reproduce**

This usually happens during animations, but can be visible on custom UI sometimes.
*I think this may have something to do with scaling?*

**Screenshots**

Video from Main Menu: https://user-images.githubusercontent.com/11298466/118180729-cade6580-b42e-11eb-8eb4-1c10e9b0ccd8.mp4
![Custom UI](https://img.tomdotbat.dev/IqSlh)

**Expected behavior**

Text renders with no artifacts and looks smooth.
![Custom UI (Viewed through Chrome)](https://img.tomdotbat.dev/wkBxr)

**Additional context**

Running in 1080p.

Custom UI that reproduces this:
```scss
.module {
	height: 60px;
	background-color: #000000;
	padding: 0 15px 0 15px;
	
	text {
		font-family: "Open Sans", sans-serif;
		font-weight: 600;
		font-size: 30px;
		
		color: white;
		
		padding-top: 7.5px;
	}
}
```

```html
<link rel="stylesheet" href="Hud.scss">

<div>
	
	<div class="module">
		<div>
			<text>POS</text>
		</div>
		<div>
			<text>1/3</text>
		</div>
	</div>
</div>
```
