### ISSUE TITLE
CSS transitions dont work on background-image

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#169]
**Describe the bug**
CSS transitions dont work on background-image

**To Reproduce**
 
1. Create a Panel with `SetClass("state", true)` and the css below
2. Do `SetClass("dying", true)`
3. The background image changes but the transition effect is not applied, same if for example removing `.dying` and adding `.healthy`

```css
.state {
    transition: all 2s ease-out;
    background-size: contain;
    width: 60px;
    height: 60px;
    margin: 20px;
}

.healthy {
    background-image: url("https://[...]/healthy.png");
}

.injured {
    background-image: url("https://[...]/injured.png");
}

.dying {
    background-image: url("https://[...]/dying.png");
}
```

**Expected behavior**
Transition should work
