### ISSUE TITLE
TextEntry.Placeholder does not auto-hide

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#1763]
**Describe the bug**
Setting a placeholder works, but not automatically hides the placeholder as soon as the TextEntry isn't empty anymore.

**To Reproduce**
1. Assign a value to a `TextEntry`'s Placeholder
2. Focus the TextEntry and enter a text - the Placeholder is still displayed

**Expected behavior**
The placeholder should get hidden automatically, e.g. via Style `Display` assignments.

**Additional context**
Tho, it isn't hard to fix this adding the snippet below, but feels unconvenient as it has to be done manually:

```scss
TextEntry:not(.has-placeholder) .placeholder {
    display: none;
}
```
