### ISSUE TITLE
Sometimes I randomly get NRE's in my UI panel

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#182]
**Describe the bug**
Exactly every second restart I get this exception:
![image](https://user-images.githubusercontent.com/1809172/118378956-e3da4880-b5df-11eb-8f94-355a632d8da4.png)
![image](https://user-images.githubusercontent.com/1809172/118378953-df159480-b5df-11eb-8a72-174dcef12b1f.png)

**Expected behavior**
Exception should not occur

**Additional context**
LobbyUI.cs
```cs
using Sandbox.UI;

namespace DeadByMidnight.UI.Lobby
{
	public partial class LobbyUI : Panel
	{
		private GameState _previousState;

		public LobbyUI()
		{  // Line 10
		        StyleSheet.Load("/UI/Lobby/LobbyUI.scss");
			AddChild<LobbyWaitingUI>();
			
			_previousState = Game.Instance.State;
		}

		public override void Tick()
		{
			base.Tick();

			if (Game.Instance.State == _previousState)
			{
				return;
			}

			Style.Display = Game.Instance.State == GameState.Lobby
				? DisplayMode.Flex
				: DisplayMode.None;

			Style.Dirty();

			_previousState = Game.Instance.State;
		}
	}
}
```
LobbyUI.scss
```scss
lobbyui {
    z-index: 999;
    height: 100%;
    width: 100%;
    position: absolute;
    top: 0;
    left: 0;
    background-color: black;
}
```
