### ISSUE TITLE
background-size does not animated using transitions

### ISSUE THREAD

**Issue by JamDoggie** [Facepunch/sbox-issues#1948]
### Describe the bug

When applying a transition on a CSS element to the property 'background-size', it doesn't animate as expected.

### To Reproduce

1. Create any element and set a background image. Maybe even set background-position to center to make it look nice when we change background-size.
2. In the element's :hover styles, set background-size to 150% or any non 100% zoom
3. give the element a transition for background-size and any timing and easing function you want, as long as it's noticeable.
4. Notice how instead of smoothly zooming in or out on the background, it is instant with no animation.

### Expected behavior

background-size should animate whenever it changes if a transition is applied to the base element. This works on all modern web browsers as far as I can tell.

### Media/Files

[S&box](https://gyazo.com/5420351b8fb9a6ec73da608ceb02eede)

[Chrome](https://gyazo.com/10af36aa19598585eaa7399979e0271e)

### Additional context

Maybe investigate into the other background properties as well like background-position, as that should probably be affected by transitions too; I haven't tried it. Also see if animations behave the same way.

**Comment by ogniK5377** [comment]
Should be fixed next update 👍

**Comment by JamDoggie** [comment]
Still seems not to transition :(

**Comment by ogniK5377** [comment]
Provide a test case and i'll take a look

**Comment by JamDoggie** [comment]
Here's some real simple HTML and CSS if that's enough:

test.html:
```html
<link rel="stylesheet" href="test.scss">

<div>
    <div class="container">
        <button class="test-button"></button>
    </div>
</div>
```

test.scss:
```scss
.test-button {
    background-image: url('https://avatars.akamai.steamstatic.com/adfd2545a3a5f0eb07ad042873be6aa4e03ef660_full.jpg');
    width: 14vmin;
    height: 14vmin;
    cursor: pointer;
    background-position: center;
    transition: background-size 0.5s ease, transform 0.5s ease;
} /* A centered button that has a transition on background-size and transform */

.test-button:hover {
    background-size: 110%;
} /* Notice that when you hover, the background size changes; there's just no animation. */

.test-button:active {
    transform: scale(1.5);
} /* Transitions work as expected on transforms, though. */

.container {
    justify-content: center;
    align-items: center;

    width: 100%;
    height: 100%;
    pointer-events: all;
} /* Boiler plate container */
```
