### ISSUE TITLE
CSS property "animation-fill-mode" not working

### ISSUE THREAD

**Issue by Hlowy** [Facepunch/sbox-issues#1960]
### Describe the bug

When changing the property "animation-fill-mode" nothing happens, but there is no warning that this property does not exist

## HTML
```html
<link rel="stylesheet" href="KeyframeTest.scss" />
```
##
## SCSS
```scss
KeyframeTest {
    width: 500px;
    height: 500px;
    background-color: red;
    position: relative;
    animation-name: scale;
    animation-duration: 1.5s;
    animation-timing-function: ease;
    animation-fill-mode: forwards;
    animation-iteration-count: 1;
}

@keyframes scale {
    from {
        background-color: blue;
        transform: scale(0);
    }

    to {
        background-color: yellow;
        transform: scale(1);
    }
}
```

### Expected behavior

Imitation of a real css property, for example, I need support for "animation-fill-mode: forwards;" to save its state at the end of the animation

### Media/Files

https://imgur.com/oXq9rRm

### Additional context

Not required
