### ISSUE TITLE
Pointer Events on child panels don't behave as expected when a parent panel has pointer-events: visible

### ISSUE THREAD

**Issue by trundler-dev** [Facepunch/sbox-issues#2015]
### Describe the bug

When `pointer-events: visible` is set in a parent panel, and `pointer-events: all` in child panels in the hover pseudo class, only the last child of the parent panel will properly receive pointer-events, despite both children receiving the hover pseudo class when hovered over.

See the reproducible below.
[pointer-events-repro.zip](https://github.com/Facepunch/sbox-issues/files/9051057/pointer-events-repro.zip)

### To Reproduce

1. Download the reproducible and load into the game.
2. Notice pointer-events are visible. You can move the mouse around and click on panels.
3. Click on the left most panel. Nothing happens.
4. Click on the right most panel. A log message is displayed in the console.

Since the second child can produce a message, but the first child can't, and the panels are identical in code and styling, we can only assume there is a bug preventing pointer-events to occur on anything but the last child.

**Practice What You've Learned**
1. Add a third ChildElementA to Hud.html and notice that the new last child is the only panel that can receive pointer events.
2. Try adding a label or any other UI element without pointer-events capabilities. Now **neither** panel can accept pointer-events on hover.
3. Replace the `&:hover { pointer-events: all }` pseudo class with `pointer-events: all` in the ChildElementA class, so pointer-events should be accepted anytime. If you still have the label as the last child of your template, **pointer events will not work at all**. However, if the last child does NOT exist, **pointer events will work for both panels as expected**. 

### Expected behavior

Pointer events should behave as expected for any child, whether stated in the hover pseudo class or otherwise.

**Comment by trundler-dev** [comment]
I can confirm this is an issue with the pointer-events property itself and not something weird about hovering, as I tried to manually get around this by checking if the Mouse position is within the bounds of the panel:

```cs
	private void CheckPanelHover()
	{
		var c = InteractionMenuContainer.Box.Rect;

		var xPos = c.Position.x;
		var yPos = c.Position.y;
		var minBoundary = new Vector2( xPos, yPos );
		var maxBoundary = new Vector2( xPos + c.Size.x, yPos + c.Size.y );

		bool mouseInBoundary = (
			Mouse.Position.x > minBoundary.x
			&& Mouse.Position.y > minBoundary.y
			&& Mouse.Position.x < maxBoundary.x
			&& Mouse.Position.y < maxBoundary.y);
		InteractionMenuContainer.SetClass( "pointer-events", mouseInBoundary );
	}
```

```scss
InteractionMenu {
    position: absolute;

    .interaction-menu-container {
        flex-direction: column;
        background-color: rgba(4, 42, 71, 1);
        position: absolute;
        opacity: 0;

        &.show {
            opacity: 1;
        }

        &.pointer-events {
            pointer-events: all;
            background-color: darkcyan;
        }
    }
    ...
}
```

Hovering will change the background color of the class successfully, meaning the class was applied, but pointer events still pass through the panel.
