### ISSUE TITLE
Hotloading Images when Updated

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#2157]
### For?

S&Box

### What can't you do?

I've been messing with some UI elements in photoshp and currently I have to restart s&box to see the changes to the image files. It'd be a nice QOL feature if the images were hotloaded after I update them.

Currently, I set them using CSS classes:
```CSS
  .torso
  {
    position: absolute;
    width: 100%;
    height: 100%;
    background-image: url("textures\ui\health\limbs\ui_limbs_torso.png");
    background-size: cover;
  }
  ```

### How would you like it to work?

Update to image file -> hotload new image in game.

### What have you tried?

Restarting s&box.
