### ISSUE TITLE
background-image adds border/shadow since the texture fix

### ISSUE THREAD

**Issue by Trojaner** [Facepunch/sbox-issues#218]
**Describe the bug**
Since yesterday my background images have a weird border

**To Reproduce**

1. Add `background-image: url("https://i.imgur.com/4Z8mqpC.png")`, observe border/shadow
2. Border disappears when background-image is removed, hence its not a CSS issue and part of the rendered image

**Expected behavior**
There should be no lines/shadow/border around the image

**Screenshots**
Image: 
![](https://i.imgur.com/4Z8mqpC.png)

Ingame:
![image](https://user-images.githubusercontent.com/1809172/118826675-5b4ff680-b8c4-11eb-96fc-c862c8fb4e01.png)

**Additional context**
```html
<div class="state healthy" @ref="StatePanel"></div>
```

```css
.state {
    background-size: contain;
    width: 40px;
    height: 40px;
    margin: 10px;

    &.healthy {
        background-image: url("https://i.imgur.com/4Z8mqpC.png");
    }
}	
```
