### ISSUE TITLE
SCSS: "flex-basis" Property Doesn’t Behave as Expected

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/sbox-issues#2255]
### Describe the bug

When I try to use the flex-basis property, it doesn't appear to do anything.

### To Reproduce

1. Create a test panel using the HTML and SCSS examples from the Media/Files section.
2. Notice that the flex items aren't divided into rows of 4 like the CodePen equivalent.

### Expected behavior

The flex-basis property should support lengths, such as 200px, 20%, etc.

### Media/Files

```html
<root>
    <div class="parent">
        <div class="child"><text>1</text></div>
        <div class="child"><text>2</text></div>
        <div class="child"><text>3</text></div>
        <div class="child"><text>4</text></div>
        <div class="child"><text>5</text></div>
        <div class="child"><text>6</text></div>
        <div class="child"><text>7</text></div>
        <div class="child"><text>8</text></div>
        <div class="child"><text>9</text></div>
        <div class="child"><text>10</text></div>
        <div class="child"><text>11</text></div>
        <div class="child"><text>12</text></div>
        <div class="child"><text>13</text></div>
        <div class="child"><text>14</text></div>
        <div class="child"><text>15</text></div>
        <div class="child"><text>16</text></div>
        <div class="child"><text>17</text></div>
        <div class="child"><text>18</text></div>
        <div class="child"><text>19</text></div>
        <div class="child"><text>20</text></div>
    </div>
</root>
```
```css
rootpanel {
    /* Nothing. */
}

.parent {
    width: 400px;
    display: flex; /* Needed for codepen example. */
    flex-wrap: wrap;
    background-color: red;
}

.child {
    flex-grow: 1;
    flex-shrink: 0;
    flex-basis: 21%;
    margin: 5px;
    height: 100px;
    background-color: blue;
}
```
In-game image:
![image](https://user-images.githubusercontent.com/16133099/187812988-55576776-8c29-496b-8a65-0225c66cac3f.png)

CodePen image:
![image](https://user-images.githubusercontent.com/16133099/187813083-a83208b2-cdfb-4bf6-9110-921b300f03ca.png)
