### ISSUE TITLE
SCSS: Universal Selector (*) Doesn't Behave as Expected

### ISSUE THREAD

**Issue by LeQuackers** [Facepunch/sbox-issues#2266]
### Describe the bug

When I try to style all elements using the universal selector (*), nothing happens.

### To Reproduce

1. Create a test panel using the HTML and SCSS examples from the Media/Files section.
2. Notice that the elements don't have background colors like the CodePen equivalent.

### Expected behavior

The universal selector (*) behaves as expected.

### Media/Files

```html
<root>
	<div class="parent">
		<div><text>foo 1</text></div>
		<text>foo 2</text>
		<span><text>foo 3</text></span>
	</div>
</root>
```
```scss
.parent {
	font-size: 128px;
}

/* Nothing. */
.parent > * {
	background-color: red;
}

/* Nothing. */
.parent * {
	background-color: red;
}

/* Nothing. */
* {
	background-color: red;
}
```
In-game image:
![image](https://user-images.githubusercontent.com/16133099/188242426-abb6f467-8fd2-4b68-823e-bf05cf6c23f5.png)
CodePen image:
![image](https://user-images.githubusercontent.com/16133099/188242655-459e8cac-dc34-4de1-9217-6a041e065d2c.png)
