### ISSUE TITLE
Allow for cursor visibility to be set in code

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#2422]
### What it is?

We used to be able to do `pointer-events: visible;` in CSS - that was removed after pointer events were reworked.

The only info I could find about making the cursor visible while passing inputs to the game was this hacky workaround: https://github.com/Facepunch/sbox-pool/commit/1b6dd5b4ea74cd1bd42f121029f636ee571a2fe9.

This involves making a 0x0 panel with `pointer-events` set to `all`, but I couldn't get this to work for me at all, so maybe there's more to it.
```css
cursorcontroller {
    position: absolute;
    left: 0px;
    top: 0px;
    width: 0px;
    height: 0px;
    display: none;
    pointer-events: all;
}
```

This is a pretty hacky solution for any game that doesn't use a first- / third-person camera, such as a strategy or simulation game.

### What should it be?

It would be nice if `pointer-events: visible` was brought back.

An alternative solution would be a setter on `Mouse.Visible` that affects cursor visibility when there's no active panel - i.e. you're not hovering over a UI element or `pointer-events` is `none`.
