### ISSUE TITLE
SCSS: Adding suffixes with the parent selector for scss files

### ISSUE THREAD

**Issue by Watermelon914** [Facepunch/sbox-issues#2788]
### For?

S&Box

### What can't you do?

I can't use the parent selector to quickly create suffixes for classes in scss files

### How would you like it to work?

https://sass-lang.com/documentation/style-rules/parent-selector#adding-suffixes
Basically, when you do 
```scss
.accordion {
  max-width: 600px;
  margin: 4rem auto;
  width: 90%;
  font-family: "Raleway", sans-serif;
  background: #f4f4f4;

  &__copy {
    display: none;
    padding: 1rem 1.5rem 2rem 1.5rem;
    color: gray;
    line-height: 1.6;
    font-size: 14px;
    font-weight: 500;

    &--open {
      display: block;
    }
  }
}
```

It compiles into
```css
.accordion {
  max-width: 600px;
  margin: 4rem auto;
  width: 90%;
  font-family: "Raleway", sans-serif;
  background: #f4f4f4;
}
.accordion__copy {
  display: none;
  padding: 1rem 1.5rem 2rem 1.5rem;
  color: gray;
  line-height: 1.6;
  font-size: 14px;
  font-weight: 500;
}
.accordion__copy--open {
  display: block;
}
```

### What have you tried?

You can get around this by just manually doing it like in the compiled css above, but it's non-ideal.
