### ISSUE TITLE
Outdated CSS: `*-content` keywords of the `height` and `width` attribute

### ISSUE THREAD

**Issue by Alf21** [Facepunch/sbox-issues#298]
**Describe the bug**
I tried to horizontally and vertically center an absolute div and came to the result, that the `fit-content` keyword in `height` and `width` attribute is not working.

In the following screenshot, you can see the result of the (S)CSS code below (the "blurred" background and the `Test` label in the upper left corner):
![image](https://user-images.githubusercontent.com/11843790/120511985-3632ac00-c3cb-11eb-8ceb-71c8570476d8.png)

**To Reproduce**
Create a panel, add a label and the corresponding (S)CSS code:
```scss
Test
{
	position: absolute;
	z-index: 100;
	font-family: Roboto;
	font-size: 23px;
	font-weight: 500;
	color: white;
	width: fit-content;
	height: fit-content;
	left: 0;
	right: 0;
	top: 0;
	bottom: 0;
	margin: auto;
	padding: 20px;
	background-color: rgba(10, 10, 10, 0.95);
}
```

Example `.cs` component could be:
```cs
using Sandbox.UI;
using Sandbox.UI.Construct;

public class Test : Panel
{
    public Label TestLabel { set; get; }

    public Test()
    {
        StyleSheet.Load("/ui/Test.scss");

        TestLabel = Add.Label("Test", "test");
    }
}
```

**Expected behavior**
If tested with the following example source code in the browser, I'm getting a different result:

```html
<html>
<head>
	<title>Test</title>
	
	<style>
	.test2 {
		position: absolute;
		z-index: 100;
		font-family: Roboto;
		font-size: 23px;
		font-weight: 500;
		color: white;
		width: fit-content;
		height: fit-content;
		left: 0;
		right: 0;
		top: 0;
		bottom: 0;
		margin: auto;
		padding: 20px;
		background-color: rgba(10, 10, 10, 0.95);
	}
	</style>
</head>
<body>
	<div class="test2">Test</div>
</body>
</html>
```
![image](https://user-images.githubusercontent.com/11843790/120511933-2b781700-c3cb-11eb-8ce2-8efdc47c4c5e.png)

**Additional context**
If you need further details, do not hesitate to ask.
