### ISSUE TITLE
`overflow: hidden` stopped working for label

### ISSUE THREAD

**Issue by timmybo5** [Facepunch/sbox-issues#3409]
### Describe the bug

The label's text is showing outside of the panel's boundaries even if overflow is hidden.

### To Reproduce

**OverflowTest.cs**
```csharp
public class OverflowTest : Panel
{
    public OverflowTest()
    {
        StyleSheet.Load("/base/ui/OverflowTest.scss");
        Add.Label("This is a very long text");
    }
}
```

**OverflowTest.scss**
```css
OverflowTest {
    position: absolute;
    width: 100%;
    height: 100%;
    justify-content: center;
    align-items: center;

    label {
        background-color: red;
        width: 100px;
        overflow: hidden;
        font-size: 40px;
    }
}
```

![image](https://github.com/sboxgame/issues/assets/4988198/01bbec53-4dca-4e2e-90dd-6ea19ac30000)

### Expected behavior

The text is clipped of at the boundary of the panel like it was before.
