### ISSUE TITLE
Stylesheet parsing error with !important on opacity

### ISSUE THREAD

**Issue by cr4yz** [Facepunch/sbox-issues#37]
Getting this error when using !important on any css tag that takes a simple int or float (i.e opacity, flex-grow)

`Error parsing stylesheet: Input string was not in the correct format.`

**Comment by rndtrash** [comment]
A blast from the past? `!imporant` doesn't work on Flexbox-related properties to me. Per [spec on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/important), it should be present for any property, except in `@keyframes` animations, and is ignored while in transition. Please reopen the issue.

```scss
.repro {
    background-color: darkorange !important;
    padding: 4px !important;
    flex-direction: row !important;
    align-items: center !important;
    justify-content: flex-start !important;
}
```

![Error log](https://github.com/user-attachments/assets/0f28861f-f043-4fc5-8284-d6e8744b12f6)
