### ISSUE TITLE
World Panels clip incorrectly if a background color isn't set

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4062]
### Describe the bug

I'm not actually entirely sure what this bug is but, if I have my world panels without a background color set, they will occasionally clip the text strangely like in this video:

https://github.com/sboxgame/issues/assets/7847372/25a03aba-ffcc-4e64-a5d0-f13991e3637d

But then if I set the background color, the strange clipping does not occur.

https://github.com/sboxgame/issues/assets/7847372/ca2986ad-36c0-429c-9333-ec3cdd986dd8

### To Reproduce

1. Create world panel with the following setup:
```CS
	public WorldNumberPanel()
	{
		var size = 300f;
		PanelBounds = new Rect { Width = size, Height = size, Position = new Vector2( -size/2f, -size/2f )};
		WorldScale = 1.5f;
	}
```
```CSS
.world-number-panel
{
  position: absolute;
  width: 100%;
  height: 100%;
  opacity: 1;
  
  background-color: rgba(#000, 0.5);
  
  justify-content: center;
  align-items: center;
  
  transition: all 2s ease-in;
  
  .label
  {
    width: 100%;
    height: 100%;
    
    color: white;
    align-items: center;
    text-align: center;
    
    font-family: $font-world-text;
    font-size: 100px;
    text-stroke: 16px black;
  }
  }
 ```
 
 ```razor
 //razor code
 <root class="world-number-panel damage-number">
	<label>50</label>
</root>
```
 2. See that changing the background color in the css changes how the panel is clipped.

### Expected behavior

Clipping doesn't occur.

### Additional context

Sorry Alex!
