### ISSUE TITLE
UI timescale is debatable

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4173]
### Describe the bug

Panels with css properties that have transitions will not animate when Scene.TimeScale = 0.

### To Reproduce

```css
button
        {
            transform: scale(1);
            transition: all 0.05s ease-in-out;
            cursor: pointer;

            &:hover
            {
                transform: scale(1.1);
            }

            &:active
            {
                transform: scale(0.9);
            }
        }
```

will work when TimeScale is 1, but not when TimeScale is 0.

### Expected behavior

CSS animations should not be affected by TimeScale. Or there should be a way to specify whether or not a transition respects timescale.
