### ISSUE TITLE
UI Sounds are no longer working with the new Audio Changes

### ISSUE THREAD

**Issue by CarsonKompon** [Facepunch/sbox-issues#4293]
### Describe the bug

![image](https://github.com/Facepunch/sbox-issues/assets/5159369/ed292755-14a8-4b66-835b-be8be25b1616)

### To Reproduce

Clone [this repo](https://github.com/carsonKompon/pizza_clicker) and launch it in editor and when you enter play mode you will instantly get the error in chat. It's also spitting tons of errors for the default sounds (may have just been removed?)
```css
&:hover
{
    sound-in: ui.button.over;
}

&:active
{
    sound-in: ui.popup.message.close;
}
```
![image](https://github.com/Facepunch/sbox-issues/assets/5159369/792ec46d-f407-4457-9b3a-e713c88f69c8)

### Expected behavior

UI Audio should play without errors and ideally the base sounds should work again (but its fine if I need to find my own replacements)
