### ISSUE TITLE
Setting the `BackgroundImage` of a panel using a texture breaks the sizing on it

### ISSUE THREAD

**Issue by Fortune117** [Facepunch/sbox-issues#4649]
### Describe the bug

In this clip you can see the initial behaviour of the crosshair changing background images when hovering over something you can interact with. Initially it is relying on this CSS:

```CSS
	.crosshair
	{
		left: 0;
		top: 0;
		width: $cross-hair-size;
		height: $cross-hair-size;
		transition: all 0.05s linear;
		
		background-color: green;
		
		background-size: cover;
		background-repeat: no-repeat;
		background-image: url("textures/ui/crosshair_icons/crosshair.png");
		image-rendering: pixelated;

		&.interact
		{
			background-image: url("textures/ui/crosshair_icons/hand_interact.png");
			width: 100px;
			height: 100px;
		}
	}
```

However, if I instead set the background image to a texture (created by right clicking a png and clicking create texture), it no longer scales correctly (the hand image doesn't fill the green square).

https://github.com/Facepunch/sbox-issues/assets/7847372/fa4753d1-34c5-4d89-bf8f-ac721d0a0bd9

If I instead set the background image using the `SetBackgroundImage` function and use the string path to the image I want it does work as expected.

e.g. `Instance.CrosshairInternal.Style.SetBackgroundImage( "textures/ui/crosshair_icons/hand_interact.png" );`

### To Reproduce

1. Create a texture from a png
2. Set the background image of a panel from code to this new texture
3. See sizing seems strange

### Expected behavior

Should work/look the same as CSS.
