### ISSUE TITLE
SCSS - can't do multiple percentages per one keyframe

### ISSUE THREAD

**Issue by DarkReaper231** [Facepunch/sbox-issues#5168]
### Describe the bug

It is not possible to write keyframes this way
```css
@keyframes tilt {
	0%, 10% {
		transform: rotate(0deg) scale(1);
		transform-origin: center;
	}
}
```
instead you have to do
```css
@keyframes tilt {
	0% {
		transform: rotate(0deg) scale(1);
		transform-origin: center;
	}
	
	10% {
		transform: rotate(0deg) scale(1);
		transform-origin: center;
	}
}
```
Trying otherwise will result in parsing error

### To Reproduce

Put this into the SCSS of razor panel
```css
@keyframes tilt {
	0%, 10% {
		transform: rotate(0deg) scale(1);
		transform-origin: center;
	}
}
```

### Expected behavior

Putting multiple percentages into one keyframe should be allowed
