### ISSUE TITLE
[Razor] Compile error when children of ButtonGroups use properties.

### ISSUE THREAD

**Issue by badandbest** [Facepunch/sbox-issues#5272]
### Describe the bug

The project fails to compile if I try to use a string property on a button's label that is inside a ButtonGroup.

### To Reproduce

To get the error, copy MyComponent.razor and replace the text in the button's label with the `@Text` property.

___

MyComponent.razor
```razor
@using Sandbox;
@using Sandbox.UI;
@inherits PanelComponent

<root>
	<ButtonGroup>
		
		<button>Replace me with property</button>

	</ButtonGroup>
</root>

@code {

	[Property]
	public string Text { get; set; }
}

``` 

<details><summary>MyComponent.razor.scss (Not actually required to replicate error)</summary>
<p>

```scss
MyComponent
{
	pointer-events: all;
	
	width: 100%;
	height: 100%;
	
	justify-content: center;
	align-items: center;
	
	ButtonGroup
	{
		width: 400px;
		height: 85px;
		gap: 10px;
		padding: 20px;

		background-color: black;
		border-radius: 20px;
	}
}

.button
{
	cursor: pointer;

	width: 100%;
	justify-content: center;
	align-items: center;

	background-color: rgba(white, 0.1);
	border-color: white;
	border-width: 5px;
	border-radius: 5px;

	.label
	{
		font-family: Poppins;
		font-size: 24px;
		font-weight: bolder;
		color: white;
	}
}
``` 

</p>
</details> 

___
You can download the whole project if that's easier for you. [project.zip](https://github.com/Facepunch/sbox-issues/files/14736497/bugtesting.zip)

### Expected behavior

Normal text works fine. The ButtonGroup button's label should be able to use the property without an error.

### Media/Files

https://github.com/Facepunch/sbox-issues/assets/91832803/ee0a88a4-9e18-4d66-ad45-6bb23d7a6d3e

[Log.log](https://github.com/Facepunch/sbox-issues/files/14736457/Log.log)
