### ISSUE TITLE
[Razor] `animation-fill-mode: none` or a default animation will apply keyframe 0 when it shouldn't

### ISSUE THREAD

**Issue by addiment** [Facepunch/sbox-issues#5273]
### Describe the bug

An animation without a fill mode or with `animation-fill-mode: none` will apply the first keyframe of animation when the animation ends. The expected behavior (using the steps to reproduce below) would be the `test` element having a blue background, but the actual background color is red.

### To Reproduce

```razor
@* file: MainMenu.razor *@
@using Sandbox;
@using Sandbox.UI;
@inherits PanelComponent

<root>
	<div class="test"></div>
</root>
```

```scss
// file: MainMenu.razor.scss
@keyframes reproduce {
	0% {
		background-color: red;
	}
	100% {
		background-color: green;
	}
}

MainMenu {
	.test {
		background-color: blue;
		animation: reproduce 1s linear;
		width: 240px;
		height: 240px;
	}
}
```

### Expected behavior

no properties should be applied after the animation finishes (as opposed to applying keyframe 0), which would result in a blue background in the reproduction example.

### Additional context

Windows 10, using Rider, s&box build ID `13834669`
