### ISSUE TITLE
box-shadow does not clear after unhovering if set in &:hover class

### ISSUE THREAD

**Issue by trundlr** [Facepunch/sbox-issues#5368]
### Describe the bug

Applying a box-shadow to an element works, but attempting to only show the box-shadow on hover will result in the box-shadow persisting after unhovering.

```scss
.my-element {
  width: 100px;
  height: 100px;
  
  &:hover {
    box-shadow: 0 0 8px black;
  }
}
```

### To Reproduce

1. Create a panel with box-shadow in &:hover
2. Hover the panel
3. Notice the box-shadow persists after unhovering

### Expected behavior

The box-shadow goes away after unhovering.
