### ISSUE TITLE
Gradient opacity doesn't blend correctly

### ISSUE THREAD

**Issue by xezno** [Facepunch/sbox-issues#5477]
### Describe the bug

Our gradient alpha blending doesn't match web behaviour

### To Reproduce

Make a panel
Give it this styling:

```scss
.gradient-test {
  width: 300px;
  height: 150px;
  background: linear-gradient( 45deg, rgba( #fe71dc, 0.1 ), rgba( #dc71fe, 0.6 ) );
}
```

It'll look like this:
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/6c5538c5-cbe3-47c8-98aa-370e540d56d3)

### Expected behavior

It should look like this
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/f6f8ff05-86ef-4b34-97dd-499b093fdf0c)

### Additional context

I'm pushing a temporary fix for this that helps a little, but still isn't correct - we should investigate the root cause of this properly.
With the fix applied:
![image](https://github.com/Facepunch/sbox-issues/assets/12881812/1ac26626-98c9-4664-a336-350b04579039)
