### ISSUE TITLE
[UI] backdrop-filter no longer affects other razor components

### ISSUE THREAD

**Issue by SolsticeSpectrum** [Facepunch/sbox-issues#5747]
### Describe the bug

It used to be that when you had a razor component set to cover entire screen with backdrop-filter, it properly applied it to other razor components as well, this no longer happens for some reason and only affects objects in the scene itself.

### To Reproduce

Do this and it won't work
```scss
YourClass {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	background-color: transparent;
	backdrop-filter: blur(10px);
}
```

### Expected behavior

It should apply the blur to other razor components as well.

### Media/Files

![image](https://github.com/Facepunch/sbox-issues/assets/38611351/3b2d9bfa-164e-4444-be44-2f080d5e0a98)
