### ISSUE TITLE
linear gradient `background` doesn't work with transition

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6034]
### Describe the bug

If you try to animate a linear gradient background it does not work.

### To Reproduce

Here is some example css
```css
MainMenuButton {
	width: 1000px;
	background: linear-gradient(to right, rgba(red, 0.9) 0%, rgba(red, 0.4) 60%, rgba(black, 0) 100%);
	transition: all 0.1s;

	text {
		color: white;
		font-weight: bold;
		font-size: 60px;
		margin: 5px 0px 5px 100px;
	}

	&:hover {
		cursor: pointer;
		background: linear-gradient(to right, rgba(red, 1.0) 0%, rgba(red, 0.5) 70%, rgba(black, 0) 100%);
	}
}

```

### Expected behavior

The linear gradient should transition over time
