### ISSUE TITLE
`filter` doesn't work with transition 

### ISSUE THREAD

**Issue by matekdev** [Facepunch/sbox-issues#6053]
### Describe the bug

If you try to animate a filter CSS style it does not work.

### To Reproduce

```css
Button {
	font-size: 18px;
	font-family: $font-main;
	font-weight: bold;
	background-color: white;
	padding: 3px 15px;
	justify-content: center;
	transition: all 2s ease-in;

	&:hover {
		cursor: pointer;
		filter: brightness(60%);
	}
}
```

### Expected behavior

I'd expect the button to get darker over `2s`
