### ISSUE TITLE
TextEntry allows for input that is outside of its bounds

### ISSUE THREAD

**Issue by SebbeJohansson** [Facepunch/sbox-issues#6274]
### Describe the bug

If you write a message that is too long in the TextEntry input field it disappears out of bounds when in a container that has overflow hidden.

### To Reproduce

1. Go to https://sbox.game/vrtx/flying-sboxman or clone it from https://github.com/SebbeJohansson/flying-sboxman
2. Start a server on a map.
3. Press enter to open chat.
4. Write a long message that goes outside of the chat box.
5. Notice how it is disappearing.

### Expected behavior

I expect it to either prevent typing (a manual max length could be an acceptable workaround) or to stay within its parent and text aline with scroll. 

### Media/Files

https://github.com/user-attachments/assets/582b8474-ed8c-4ec2-af18-862865ac6e7e

### Additional context

Same issue can be found in Nicked and Sandbox Classic.

**Comment by CarsonKompon** [comment]
TextEntry has a `Multiline` bool which can be set to true to prevent this. This default behaviour is because it is assumed that most text entries are only going to be used for a single line of text. 
You could also do this through CSS if you'd like (which is how the `Multiline` bool works under the hood)

`Multiline` method:
```razor
<TextEntry Multiline="@true"></TextEntry>
```

CSS method:
```css
.textentry
{
    align-items: flex-start;
    white-space: normal;
}
```

**Comment by SebbeJohansson** [comment]
@CarsonKompon thanks for the partial workaround! Sadly it didn't help us get all the way. This didn't keep it on one like nor make it similar to other input fiends in games and websites.

Would like some additional feature to the text entry component that can fully allow for the ui we want!

**Comment by CarsonKompon** [comment]
> Would like some additional feature to the text entry component that can fully allow for the ui we want!

I believe you totally can achieve what you're looking for. You just want to have a Panel that contains your TextEntry:
```razor
<div class="input-field">
  <TextEntry />
</div>
```

And then give the `input-field` class a max-height and scrolling capabilities:
```scss
.input-field
{
    max-height: 48px;
    overflow-y: scroll;
    
    .textentry
    {
        align-items: flex-start;
        white-space: normal;
    }
}
```

**Comment by SebbeJohansson** [comment]
@CarsonKompon I must be doing something wrong. This seems to be scrolling vertically instead of horizontally, and not keeping it focused on where the caret is.

**Comment by CarsonKompon** [comment]
Oh I didn't realize you wanted it to scroll horizontally, my mistake.

This is all you really want then:
```scss
.input-field
{
    overflow-x: scroll;
}
```
