### ISSUE TITLE
Videos used as backgrounds in UI get stretched in game, but not in the editor

### ISSUE THREAD

**Issue by SebbeJohansson** [Facepunch/sbox-issues#6275]
### Describe the bug

When using a video as a background in UI the background looks find in the editor, but when opened in game it is stretched.
This is with the proper CSS rules.

### To Reproduce

1. Either go to https://sbox.game/vrtx/flying-sboxman or clone it from https://github.com/SebbeJohansson/flying-sboxman
2. Start the menu scene.
3. Notice that it is stretched in Game.

### Expected behavior

I expect the video to look "correct" or at least look the same in the two enviroemnts.environments

### Media/Files

In Game:
![image](https://github.com/user-attachments/assets/77d7607c-6456-4292-b30f-1b0d5bfa1b42)

In the editor:
![image](https://github.com/user-attachments/assets/6958f865-d96d-420c-aa14-c555d2cf0528)

Code:
`MainMenuPanel.razor`
```razor
@namespace Vrtx.UI
@inherits PanelComponent

<root>
    <MainMenuRoot />
</root>
```
`MainMenuPanel.razor.scss`
```scss

@import "/UI/Styles/Index.scss";
MainMenuRoot {
    width: 100%;
    height: 100%;
    pointer-events: all;
    background-image: url('ui/videos/sausage_boy_walking.mp4');
    background-size: cover;
    background-position: center;
}
```

### Additional context

I have seen this happening to other games.
