### ISSUE TITLE
@keyframes in SCSS

### ISSUE THREAD

**Issue by DangerKiddy** [Facepunch/sbox-issues#651]
**What can't you do?**
I want to make a complex animations like in css, using @keyframes

(example of not that complex, but an animation. Another example could be glitch text)
```css
@keyframes animation-name { 
  0% { 
 color: pink; 
  } 
  50% { 
 color: yellow; 
  } 
  100% {
 color: blue;
 }
}
```

**How would you like it to work?**
Exactly/Almost the same like in CSS

**Additional context**
