### ISSUE TITLE
[Razor] border-image-width-top/left/right/bottom not working as expected

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#6552]
### Describe the bug

border-image-width-top/left/right/bottom does not work like you would expect it to.
A border width of 0 does not make the side stop appearing, and only extremely high width values have any sort of noticeable effect, 
https://github.com/user-attachments/assets/4d6f7c1e-1a3c-4ced-89a5-f30180bb3322
If this is intentional behavior this is very unclear and I would expect the border-image-width to control the width of the border

### To Reproduce

```html
<div class="border"></div>
```
```scss
.border{
	border-image: linear-gradient(to right, white, black) 15;
	border-image-width-top: 0px;
}
```

### Expected behavior

border-image-width-top/left/right/bottom should control the width of their respective sides.
If this is intentional then I don't believe there's anyway to currently make a border gradient on a specific side without just making a wannabe border (a div that just uses background-image) as border-top/left/right/bottom have no control over the width of the div as well. Which seems to be able to work fine in this example on [css-tricks](https://css-tricks.com/gradient-borders-in-css/)

**Comment by xezno** [comment]
This is intentional, if you want to use that property then you have to specify all the slices, like this:

```scss
.border {
	width: 256px;
	height: 64px;
	background-color: #0f0;

	border-image: linear-gradient(to right, white, black) 0 0 15 0;
	border-image-width-bottom: 256px;
}
```
![Image](https://github.com/user-attachments/assets/5289b45c-8cc0-4c77-8b2e-9c862deda1fb)
