### ISSUE TITLE
Length.Auto  and/or width: auto isn't working properly?

### ISSUE THREAD

**Issue by DangerKiddy** [Facepunch/sbox-issues#662]
**Describe the bug**
When using transitions in SCSS or editing style in C#, width(and maybe height as well) is supposed to change its value from `0` to `auto` for nice sliding transition, and back from `auto` to `0`:
![b267dbc20b61a7257b5eeb8ba8542664 (1)](https://user-images.githubusercontent.com/42438297/129088833-d23ce81b-5fc8-47f2-bfb8-be4badb0d57f.gif)
(gif above is using actual length in width (about 120px), instead of `auto`)

But instead, it keeps width on `0`
![63b733c72778a6ca14977f52cfffbf52](https://user-images.githubusercontent.com/42438297/129090549-6f04a11d-dc10-46a1-8a82-cf0f1c5e329a.gif)

**To Reproduce**

1. Create SCSS with this class and parameters:
```scss
EntityDisplay
{
	width: 100%;
	height: 100%;
	display: flex;
	
	justify-content: center;
	align-items: center;
	text-align: center;

	font-size: 27px;
	color: white;
	opacity: 1;

	justify-content: center;
	align-items: center;
	text-align: center;
	label
	{
		transition: background-color 0.2s ease-out 0s, opacity 0.2s ease-out 0.2s, color 0.2s ease-out 0.2s, width 0.2s ease-out 0.2s;
		opacity: 0;

		width: 0;

		overflow: hidden;
		
		color: transparent;
		background-color: rgba( white, 1 );
		backdrop-filter: blur(10px);
		padding: 5px 5px 5px 5px;
		
		display: table-cell;
   		white-space: nowrap;
	}

	z-index: 1;
}

.enthover EntityDisplay label {
    transition: background-color 0.2s ease-out 0.2s, opacity 0.2s ease-out 0s, color 0.2s ease-out 0.2s, width 0.2s ease-out 0s;

	color: white;
	background-color: rgba( black, 0.5 );
	
    opacity: 1;
    width: auto;

    transform: scale( 1 );
}
```
2. Then in C#:
```csharp
// in your hud
RootPanel.AddChild<EntityDisplay>();

//...

public class EntityDisplay : Panel
{
	public Label label;
	public EntityDisplay()
	{
		label = Add.Label( "", "value" );
	}

	public override void Tick()
	{
		base.Tick();

		var EyePos = Local.Pawn.EyePos;

		var tr = Trace.Ray( EyePos, EyePos + Local.Pawn.EyeRot.Forward * 85 )
			.Radius( 2 )
			.Ignore( Local.Pawn )
			.Run();

		if ( tr.Entity == null )
		{
			Parent.SetClass( "enthover", false );

			return;
		}

		Parent.SetClass( "enthover", true );

		label.Text = "An Entity";
	}
}
```
3. Hover on any entity you like
4. See the thing

**Expected behavior**
When setting width (or whatever) to `auto`, it would act exactly the same like in CSS, so it would fit the content (Like on the first gif)
