### ISSUE TITLE
SCSS calc 

### ISSUE THREAD

**Issue by DangerKiddy** [Facepunch/sbox-issues#723]
**What can't you do?**
```scss
someThing
{
    width: calc(100% - 10px);
}
```

**How would you like it to work?**
Exactly like in the css

**What have you tried?**
```scss
someThing
{
    width: calc(100% - 10px);
}
// and

someThing
{
    width: 100% - 10px;
}
```

**Additional context**
Not sure is it dublicate cuz haven't found it anywhere
