### ISSUE TITLE
WorldPanel Alignment Jank (labels..? disappearing with "overflow: hidden" and old culling issue)

### ISSUE THREAD

**Issue by Manonox** [Facepunch/sbox-issues#7389]
### Describe the bug

WorldPanel Alignment properties are breaking labels (and maybe some other elements) and causing incorrect culling
Elements get fucked when both HAlignment and VAlignment are not "Center"
Panel gets frustrum culled if you don't look at its origin if you have HAlignment **AND/OR** VAlignment not on "Center"

### To Reproduce

1. Make a PanelComponent with some nested divs and deep labels
2. Make a WorldPanel
3. Set `overflow: hidden` in css for the root
4. Fiddle around with alignment properties

### Expected behavior

- Labels being fine
- WorldPanel should still be rendered if part of it is on screen

### Media/Files

Text disappearing
https://github.com/user-attachments/assets/8ba8c8a0-181a-4db0-9bc0-5fe914b7ffa7

Culling issue
https://github.com/user-attachments/assets/35f78797-59e7-4afd-ae15-8792e5e70874

### Additional context

Minimal razor panel setup to break the label (from the attached video)

```razor
<root>
	<div id="header">
		<div id="name">Poor Label</div>
	</div>
</root>
```

```scss
Something {
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	background-color: black;
	font-weight: bold;
	border-radius: 16px;
	overflow: hidden; // evil mf
	font-family: Poppins;
	color: white;
	flex-direction: column;

	#header {
		position: relative;
		width: 100%;
		
		font-size: 20px;
		height: 1.4em;
		
		justify-content: center;
		align-items: center;

		background-color: gray;
	}
```
