### ISSUE TITLE
[UI] Some elements have deadzones

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#7528]
### Describe the bug

Some elements seem to have a weird quirk where, despite the rest of the element being fine, theres inexplicable deadzones in certain areas, it seems this is probably a border issue? This can be very obviously shown by the s&box main menu, clicking certain areas on the "Unplayed", "Updated", etc tags will sometimes ignore the user's input. Which, as with most UI, feels pretty terrible.

https://github.com/user-attachments/assets/974bfa86-8e14-4b18-bd00-9a1eb39b4c80

I'm experiencing this in my own game as well, and I imagine the issue I have and the issue on the main menu are related. 

### To Reproduce

1. Open s&box
2. Click the "Unplayed", blah blah blah, tags
3. In certain areas, there will be deadzones, the entire tag is not a deadzone, however, as there *are* places you can actually click and get the modal. 

### Expected behavior

The entire element should be clickable and responsive

**Comment by CarsonKompon** [comment]
So the UNPLAYED badge on the menu didn't have `pointer-events: none`, so it was eating the input of anything layered underneath it. I have added that and now it works as intended, probably all that you're missing as well.

An issue you may still be experiencing though can be seen in the following video, where you have a button that moves downward when pressed, so your cursor is no longer hovering over it when OnClick/OnMouseReleased is run. (You can tell because when the mouse is no longer on it the highlight goes away).

https://github.com/user-attachments/assets/b75e7a93-0af0-4133-a0b2-cdd5faa03cb1

This is probably something we can solve where translateX() will offset the visual but not the actual rect you're meant to click. Will investigate

**Comment by Retroeer** [comment]
TabButton.razor
```html
<root class="@( Selected ? "selected" : "" )" 
      onclick=@( () => Clicked?.Invoke() )>

	<i class="material-icons">@Icon</i>
	<span>@Text</span>
</root>
```
```cs
@code {
	public Action Clicked { get; set; }
	public bool Selected { get; set; }
	public string Icon { get; set; }
	public string Text { get; set; }

	protected override int BuildHash() => HashCode.Combine( Icon, Text );
}
```

TabButton.razor.scss
```scss
TabButton {
  padding: 10px;
  color: white;
  font-size: 24px;
  flex-shrink: 0;
  align-items: center;
  font-family: "Helvetica Rounded";
  justify-content: center;
  border: transparent 1px;
  
  .material-icons {
    font-size: 24px;
    margin-top: 3px;
    align-self: center;
    justify-content: center;
    padding-right: 5px;
  }
  &:hover {
    cursor: pointer;
    border-bottom: white 1px;
  }

  &:active {
    border-bottom: white 1px;
    transform: scale(0.97);
  }

  &.selected {
    border-bottom: white 1px;
  }
}
```

If you throw this tab on something and Log for when the Click event is pressed you should be able to find it somewhere (ignore the shit scss)
