### ISSUE TITLE
CSS: border-radius does not work in transition, but works with transition all

### ISSUE THREAD

**Issue by jacobc16** [Facepunch/sbox-issues#7543]
### Describe the bug

You are unable to do `transition: border-radius` as it does not do anything. You can use `transition: all` and it will make the radius transition as expected.

### To Reproduce

TransitionBug.razor
```razor
@inherits PanelComponent
@namespace Sandbox

<root>
	<div class="items">
		<div class="broken"></div>
		<div class="working"></div>
	</div>
</root>
```

TransitionBug.razor.scss
```scss
TransitionBug
{
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	justify-content: center;
	pointer-events: all;
	
	.items {
		width: 100%;
		justify-content: center;
		align-items: center;
		gap: 20px;
	}
	
	.broken, .working {
		width: 300px;
		height: 300px;
		border-radius: 0;
		
		&:hover {
			border-radius: 20px;
		}
	}
	
	.broken {
		background-color: red;
                // This should work, but does not
		transition: border-radius 500ms linear;
	}
	
	.working {
		background-color: green;
		transition: all 500ms linear;
	}
}
```

### Expected behavior

`transition: border-radius` should make the border transition like with `transition: all`

### Media/Files

https://github.com/user-attachments/assets/6aa63268-c57c-4c2a-946e-42d01b7df6fe
