### ISSUE TITLE
CSS: transition does not affect border-radius when using a percent value

### ISSUE THREAD

**Issue by jacobc16** [Facepunch/sbox-issues#7544]
### Describe the bug

Transitions do not affect border-radius if you use a percent as its value

### To Reproduce

TransitionBug.razor
```razor
@inherits PanelComponent
@namespace Sandbox

<root>
	<div class="items">
		<div class="broken"></div>
	</div>
</root>
```
TransitionBug.razor.scss
```scss
TransitionBug
{
	position: absolute;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	justify-content: center;
	pointer-events: all;
	
	.items {
		width: 100%;
		justify-content: center;
		align-items: center;
		gap: 20px;
	}
	
	.broken {
		width: 300px;
		height: 300px;
		border-radius: 0;
                background-color: red;
		transition: all 500ms linear;
		
		&:hover {
                        // This does not work
			border-radius: 50%;
		}
	}
}
```

### Expected behavior

The `border-radius` should be transitioning

### Media/Files

https://github.com/user-attachments/assets/4b1f7a45-776f-444a-af6c-90dded0e07e6
