### ISSUE TITLE
<root> is rendered regardless of if it's *actually* being ran

### ISSUE THREAD

**Issue by Retroeer** [Facepunch/sbox-issues#8131]
### Describe the bug

If you have something like 
```scss
ExampleUI
{
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: #1a1a1a;
    justify-content: center;
    align-items: center;
    font-weight: bold;
    border-radius: 20px;
}
```
```cs
@if ( !IsActive )
{
    return;
}
<root>
</root>
```

The background-color is rendered, even if IsActive is false, this behaviour makes zero sense, as this applies to everything *within* the root, except the root itself.

### To Reproduce

Copy and paste the above code
<root> is always rendered, regardless of IsActive, if you put anything inside of <root> it will work as you would expect

### Expected behavior

Root should not be getting rendered, as this doesn't align with how, well, literally everything else works in razor
