### ISSUE TITLE
[Razor] :active should take priority over :hover

### ISSUE THREAD

**Issue by bub-bl** [Facepunch/sbox-issues#8245]
### Describe the bug

If you use the following code on a div, the :hover tag avoid the css properties to be applied in the :active tag
```scss
    &:active {
        // This property will not be applied, because the :hover already have a transform scale set
        transform: scale(.9);
    }
    
    &:hover {
        transform: scale(1.1);
        z-index: 10;
    }
```

### To Reproduce

Above

### Expected behavior

The transform scale should be applied when :active
