### ISSUE TITLE
SCSS: Cannot read color variables inside functions being declared as a variable

### ISSUE THREAD

**Issue by dhost21-en-liten-genvag** [Facepunch/sbox-issues#847]
**Describe the bug**
Cannot read colors inside functions being declared as other variables such as variables for gradients.

**To Reproduce**

1. Try adding the following code as SCSS:
```scss
$primary-color: #36CEDC;
$secondary-color: #5889E3;

$menu-background: linear-gradient($primary-color, $secondary-color);

.background {
    background: $menu-background;
}
```

**Expected behavior**
The gradient should be created from the provided variables.

**Screenshots**
https://steamuserimages-a.akamaihd.net/ugc/1695030887557323651/5F9A2D342C25D5EDD2B6AD7D668A67ED20E6CA16/?imw=5000&imh=5000&ima=fit&impolicy=Letterbox&imcolor=%23000000&letterbox=false

**Additional context**
None
