### ISSUE TITLE
Multi-line comments don't work in SCSS outside of children

### ISSUE THREAD

**Issue by ogniK5377** [Facepunch/sbox-issues#88]
**Describe the bug**
Multilined comments in SCSS files `/* */` files don't seem to work. Stacktrace as follows:

Error parsing stylesheet: Index and length must refer to a location within the string. (Parameter 'length')
![image](https://user-images.githubusercontent.com/25727384/116869112-74657000-ac53-11eb-8dd3-518425c77c5f.png)

**To Reproduce**
```cs
// Foo.cs
public class Foo : Panel
{
    public Foo()
    {
        StyleSheet.Load("/ui/Foo.scss");
    }
}
```

```scss
// Foo.scss
Foo {
    position: absolute;
    background-color: red;
    left: 10px;
    right: 10px;
    top: 10px;
    bottom: 10px;
};

/* This should work however
it seems to fail */
```

**Expected behavior**
No error should be thrown and the stylesheet should parse properly

**Screenshots**

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.
