### ISSUE TITLE
`background-color` is affecting the whole screen.

### ISSUE THREAD

**Issue by sanny-io** [Facepunch/sbox-issues#896]
**Describe the bug**
The `background-color` property is affecting the whole screen rather than the elements I'm targeting.

**To Reproduce**

```html
<link rel="stylesheet" href="sample.scss">

<div class="main">
	<div class="container">
		<text class="title">Sample</text>
	</div>

	<div class="container">
		<text class="title">Sample2</text>
	</div>

	<chatbox></chatbox>
</div>
```

```css
text.title
{
	font-family: Poppins;
	font-size: 50px;
	font-weight: 900;
	color: white;
	text-shadow: 5px 5px 50px rgba( black, 0.8 );
}

.main {
	flex-direction: column;
}

.container {
	margin: 50px;
	background-color: red;
	height: 300px;
	width: 300px;
}
```

**Expected behavior**
Only the containers should have a red background.

**Screenshots**

# What it looks like

![](https://i.imgur.com/bsQyUgK.png)

# What it should look like

![](https://i.imgur.com/b7Zq3eg.png)

**Additional context**

Add any other context about the problem here, like hardware/software information you think might make this easier to diagnose.
